<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4BB1CT5" name="Academy.FrameworkPractice.ValidateAssertion" tests="2" failures="0" timestamp="13 Feb 2021 17:31:50 GMT" time="4.317" errors="1">
  <testcase name="ValidateText" time="4.212" classname="Academy.FrameworkPractice.ValidateAssertion">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;[Valentine&#039;s Day Gift Shop]&gt; but was:&lt;[Discover Black History Makers]&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[Valentine's Day Gift Shop]> but was:<[Discover Black History Makers]>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at Academy.FrameworkPractice.ValidateAssertion.ValidateText(ValidateAssertion.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- ValidateText -->
  <testcase name="ValidateTextField" time="0.105" classname="Academy.FrameworkPractice.ValidateAssertion"/>
</testsuite> <!-- Academy.FrameworkPractice.ValidateAssertion -->
